slogan: "Keep and carry on."

show_heart: true

show_slogan: true

menu:
  - title: HOME
    url: http://cips.nyist.edu.cn
    intro: "All the articles."
    # icon: "fa fa-archive"
  - title: EVENTS
    url: categories
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: BLOG
    url: tags
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: OJ
    url: about
    intro: "About me."
    # icon: "fa fa-user"
  - title: MIRRORS
    url: atom.xml
    intro: "Subscribe me."
    # icon: "fa fa-user"

links:
  - title: "使用帮助"
    url: https://github.com/wzpan/hexo-theme-freemind
    intro: "Freemind's Github repository."
    icon: "fa fa-github"
  - title: "服务器状态"
    url: https://github.com/kristopolous/BOOTSTRA.386
    intro: "BOOTSTRA.386's Github repository."
    icon: "fa fa-github"
  - title: "同步状态"
    url: https://github.com/blackshow/hexo-theme-freemind.386
    intro: "Freemind.386's Github repository."
    icon: "fa fa-github"
  - title: "南阳理工学院CIPS协会"
    url: http://www.github.com/blackshow
    intro: "My Github account."
    icon: "fa fa-github"
  - title: "镜像管理器源码"
    url: http://www.linkedin.com/in/xxx
    intro: "My Linkin account."
    icon: "fa fa-linkedin"
  - title: "自定义镜像管理器脚本"
    url: http://www.linkedin.com/in/xxx
    intro: "My Linkin account."
    icon: "fa fa-linkedin"

widgets:
- search
# - category
# - tagcloud
- recent_news
- downloads
- contact_us
- links
- friends

rss: 
fancybox: false
favicon: favicon.png
duoshuo_shortname:


# Analytics (change to yours)
google_analytics:
  enable: false
  siteid: UA-70812759-1
baidu_tongji:
  enable: false
  siteid: cb5448498d7169c668b07c2b255d62c1

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
