slogan: "Code Together, Soar Forever."

show_heart: true

show_slogan: true

menu:
  - title: HOME
    url: http://cips.nyist.edu.cn
    intro: "All the articles."
    # icon: "fa fa-archive"
  - title: EVENTS
    url: http://cips.nyist.edu.cn/event
    intro: "All the categories."
    # icon: "fa fa-folder"
  - title: BLOG
    url: http://cips.nyist.edu.cn/blog
    intro: "All the tags."
    # icon: "fa fa-tags"
  - title: OJ
    url: http://oj.nyist.edu.cn/
    intro: "About me."
    # icon: "fa fa-user"


links:
  - title: "使用帮助(加急制作中)"
    url: /help/
    icon: "fa fa-check"
  - title: "服务器状态"
    url: /status/#server-status
    icon: "fa fa-cloud"
  - title: "同步状态"
    url: /status/#syncing-status
    icon: "fa fa-spinner"
  - title: "南阳理工学院CIPS协会"
    url: http://cips.nyist.edu.cn
    icon: "fa fa-github"
  - title: "镜像管理器源码"
    url: https://github.com/tuna/tunasync
    icon: "fa fa-code"
  - title: "自定义镜像管理器脚本"
    url: https://github.com/tuna/tunasync-scripts
    icon: "fa fa-cogs"

widgets:
# - search
# - category
# - tagcloud
- recent_news
- downloads
- contact_us
- links
- friends

rss: 
fancybox: false
favicon: cips_logo.svg
duoshuo_shortname:


# Analytics (change to yours)
google_analytics:
  enable: false
  siteid: UA-70812759-1
baidu_tongji:
  enable: false
  siteid: cb5448498d7169c668b07c2b255d62c1

# search
#swiftype_key: ZP2ZSuHgipSZfRyU8uTR
